#pragma once

#include "hft/types.hpp"

#include <cstdint>
#include <type_traits>
#include <string_view>
#include <ostream>

namespace hft {

/**
 * @brief Resting limit order representation in the order book.
 */
struct Order {
    OrderId   id{0};
    Price     price{0};
    Quantity  initial_qty{0};
    Quantity  remaining_qty{0};
    Side      side{Side::Buy};
    OrderType type{OrderType::Limit};
    Timestamp timestamp{0};

    [[nodiscard]] constexpr bool is_filled() const noexcept {
        return remaining_qty == 0;
    }

    [[nodiscard]] constexpr Quantity executed_qty() const noexcept {
        return initial_qty - remaining_qty;
    }

    constexpr bool operator==(const Order& other) const noexcept {
        return id == other.id &&
               price == other.price &&
               initial_qty == other.initial_qty &&
               remaining_qty == other.remaining_qty &&
               side == other.side &&
               type == other.type &&
               timestamp == other.timestamp;
    }
};

/**
 * @brief Trade match event generated by the matching engine.
 */
struct Trade {
    TradeId   trade_id{0};
    OrderId   resting_order_id{0};
    OrderId   incoming_order_id{0};
    Price     price{0};
    Quantity  quantity{0};
    Side      aggressor_side{Side::Buy};
    Timestamp timestamp{0};

    constexpr bool operator==(const Trade& other) const noexcept {
        return trade_id == other.trade_id &&
               resting_order_id == other.resting_order_id &&
               incoming_order_id == other.incoming_order_id &&
               price == other.price &&
               quantity == other.quantity &&
               aggressor_side == other.aggressor_side &&
               timestamp == other.timestamp;
    }
};

/**
 * @brief Compact 32-byte order event.
 */
struct OrderEvent {
    EventType type{EventType::Add};
    Side      side{Side::Buy};
    uint8_t   pad[6]{0};
    OrderId   id{0};
    Price     price{0};
    Quantity  qty{0};

    static constexpr OrderEvent make_add(OrderId order_id, Side order_side, Price limit_price, Quantity quantity) noexcept {
        OrderEvent ev{};
        ev.type = EventType::Add;
        ev.side = order_side;
        ev.id = order_id;
        ev.price = limit_price;
        ev.qty = quantity;
        return ev;
    }

    static constexpr OrderEvent make_cancel(OrderId order_id) noexcept {
        OrderEvent ev{};
        ev.type = EventType::Cancel;
        ev.id = order_id;
        return ev;
    }

    static constexpr OrderEvent make_modify(OrderId order_id, Price new_price, Quantity new_qty) noexcept {
        OrderEvent ev{};
        ev.type = EventType::Modify;
        ev.id = order_id;
        ev.price = new_price;
        ev.qty = new_qty;
        return ev;
    }

    constexpr bool operator==(const OrderEvent& other) const noexcept {
        return type == other.type &&
               side == other.side &&
               id == other.id &&
               price == other.price &&
               qty == other.qty;
    }
};

static_assert(sizeof(OrderEvent) == 32, "OrderEvent must be exactly 32 bytes");
static_assert(std::is_trivially_copyable_v<OrderEvent>, "OrderEvent must be trivially copyable");
static_assert(std::is_standard_layout_v<OrderEvent>, "OrderEvent must have standard layout");

/**
 * @brief Cache-aligned 64-byte ingress order request.
 *
 * Ingress order command fitting exactly one 64-byte hardware cache line.
 */
struct alignas(64) OrderCommand {
    OrderId   order_id{0};
    uint32_t  instrument_id{0};
    uint32_t  client_id{0};
    EventType type{EventType::Add};
    Side      side{Side::Buy};
    OrderType order_type{OrderType::Limit};
    uint8_t   pad[5]{0};
    Price     price{0};
    Quantity  qty{0};
    Timestamp timestamp{0};
    uint8_t   reserved[16]{0};

    static constexpr OrderCommand make_add(OrderId id, uint32_t instrument, uint32_t client,
                                          Side side, Price price, Quantity qty,
                                          Timestamp ts = 0) noexcept {
        OrderCommand cmd{};
        cmd.order_id = id;
        cmd.instrument_id = instrument;
        cmd.client_id = client;
        cmd.type = EventType::Add;
        cmd.side = side;
        cmd.order_type = OrderType::Limit;
        cmd.price = price;
        cmd.qty = qty;
        cmd.timestamp = ts;
        return cmd;
    }

    static constexpr OrderCommand make_cancel(OrderId id, uint32_t instrument, uint32_t client,
                                             Timestamp ts = 0) noexcept {
        OrderCommand cmd{};
        cmd.order_id = id;
        cmd.instrument_id = instrument;
        cmd.client_id = client;
        cmd.type = EventType::Cancel;
        cmd.timestamp = ts;
        return cmd;
    }

    static constexpr OrderCommand make_modify(OrderId id, uint32_t instrument, uint32_t client,
                                             Side side, Price new_price, Quantity new_qty,
                                             Timestamp ts = 0) noexcept {
        OrderCommand cmd{};
        cmd.order_id = id;
        cmd.instrument_id = instrument;
        cmd.client_id = client;
        cmd.type = EventType::Modify;
        cmd.side = side;
        cmd.order_type = OrderType::Limit;
        cmd.price = new_price;
        cmd.qty = new_qty;
        cmd.timestamp = ts;
        return cmd;
    }

    constexpr bool operator==(const OrderCommand& other) const noexcept {
        return order_id == other.order_id &&
               instrument_id == other.instrument_id &&
               client_id == other.client_id &&
               type == other.type &&
               side == other.side &&
               order_type == other.order_type &&
               price == other.price &&
               qty == other.qty &&
               timestamp == other.timestamp;
    }
};

static_assert(sizeof(OrderCommand) == 64, "OrderCommand must be exactly 64 bytes");
static_assert(alignof(OrderCommand) == 64, "OrderCommand must be 64-byte aligned");
static_assert(std::is_trivially_copyable_v<OrderCommand>, "OrderCommand must be trivially copyable");
static_assert(std::is_standard_layout_v<OrderCommand>, "OrderCommand must have standard layout");

inline std::ostream& operator<<(std::ostream& os, const OrderCommand& cmd) {
    return os << "OrderCommand{id=" << cmd.order_id
              << ", inst=" << cmd.instrument_id
              << ", type=" << cmd.type
              << ", side=" << cmd.side
              << ", price=" << cmd.price
              << ", qty=" << cmd.qty << "}";
}

/**
 * @brief Execution report event types emitted by the order gateway.
 */
enum class ExecutionType : uint8_t {
    New = 1,
    RiskRejected = 2,
    EngineRejected = 3,
    Trade = 4,
    Cancelled = 5,
    Modified = 6
};

constexpr std::string_view to_string(ExecutionType type) noexcept {
    switch (type) {
        case ExecutionType::New:            return "NEW";
        case ExecutionType::RiskRejected:   return "RISK_REJECTED";
        case ExecutionType::EngineRejected: return "ENGINE_REJECTED";
        case ExecutionType::Trade:          return "TRADE";
        case ExecutionType::Cancelled:      return "CANCELLED";
        case ExecutionType::Modified:       return "MODIFIED";
    }
    return "UNKNOWN";
}

inline std::ostream& operator<<(std::ostream& os, ExecutionType type) {
    return os << to_string(type);
}

/**
 * @brief Cache-aligned 64-byte normalized execution report.
 */
struct alignas(64) ExecutionReport {
    OrderId       order_id{0};
    uint64_t      exec_id{0};
    Price         price{0};
    Quantity      last_qty{0};
    Quantity      leaves_qty{0};
    Timestamp     timestamp{0};
    uint32_t      instrument_id{0};
    uint32_t      client_id{0};
    ExecutionType exec_type{ExecutionType::New};
    Side          side{Side::Buy};
    RiskCode      risk_code{RiskCode::Approved};
    OrderResult   engine_result{OrderResult::Accepted};
    uint8_t       pad[4]{0};

    static constexpr ExecutionReport make_risk_rejected(OrderId id, uint32_t inst, uint32_t client,
                                                        Side side, Price price, [[maybe_unused]] Quantity qty,
                                                        RiskCode code, uint64_t exec_id,
                                                        Timestamp ts = 0) noexcept {
        ExecutionReport rep{};
        rep.order_id = id;
        rep.exec_id = exec_id;
        rep.price = price;
        rep.last_qty = 0;
        rep.leaves_qty = 0;
        rep.timestamp = ts;
        rep.instrument_id = inst;
        rep.client_id = client;
        rep.exec_type = ExecutionType::RiskRejected;
        rep.side = side;
        rep.risk_code = code;
        rep.engine_result = OrderResult::Accepted;
        return rep;
    }

    static constexpr ExecutionReport make_engine_rejected(OrderId id, uint32_t inst, uint32_t client,
                                                          Side side, Price price, [[maybe_unused]] Quantity qty,
                                                          OrderResult res, uint64_t exec_id,
                                                          Timestamp ts = 0) noexcept {
        ExecutionReport rep{};
        rep.order_id = id;
        rep.exec_id = exec_id;
        rep.price = price;
        rep.last_qty = 0;
        rep.leaves_qty = 0;
        rep.timestamp = ts;
        rep.instrument_id = inst;
        rep.client_id = client;
        rep.exec_type = ExecutionType::EngineRejected;
        rep.side = side;
        rep.risk_code = RiskCode::Approved;
        rep.engine_result = res;
        return rep;
    }

    static constexpr ExecutionReport make_new(OrderId id, uint32_t inst, uint32_t client,
                                             Side side, Price price, Quantity resting_qty,
                                             uint64_t exec_id, Timestamp ts = 0) noexcept {
        ExecutionReport rep{};
        rep.order_id = id;
        rep.exec_id = exec_id;
        rep.price = price;
        rep.last_qty = 0;
        rep.leaves_qty = resting_qty;
        rep.timestamp = ts;
        rep.instrument_id = inst;
        rep.client_id = client;
        rep.exec_type = ExecutionType::New;
        rep.side = side;
        rep.risk_code = RiskCode::Approved;
        rep.engine_result = OrderResult::Accepted;
        return rep;
    }

    static constexpr ExecutionReport make_trade(OrderId id, uint32_t inst, uint32_t client,
                                               Side side, Price exec_price, Quantity fill_qty,
                                               Quantity remaining_leaves, uint64_t exec_id,
                                               Timestamp ts = 0) noexcept {
        ExecutionReport rep{};
        rep.order_id = id;
        rep.exec_id = exec_id;
        rep.price = exec_price;
        rep.last_qty = fill_qty;
        rep.leaves_qty = remaining_leaves;
        rep.timestamp = ts;
        rep.instrument_id = inst;
        rep.client_id = client;
        rep.exec_type = ExecutionType::Trade;
        rep.side = side;
        rep.risk_code = RiskCode::Approved;
        rep.engine_result = OrderResult::Accepted;
        return rep;
    }

    static constexpr ExecutionReport make_cancelled(OrderId id, uint32_t inst, uint32_t client,
                                                    Side side, Quantity cancelled_qty,
                                                    uint64_t exec_id, Timestamp ts = 0) noexcept {
        ExecutionReport rep{};
        rep.order_id = id;
        rep.exec_id = exec_id;
        rep.price = 0;
        rep.last_qty = cancelled_qty;
        rep.leaves_qty = 0;
        rep.timestamp = ts;
        rep.instrument_id = inst;
        rep.client_id = client;
        rep.exec_type = ExecutionType::Cancelled;
        rep.side = side;
        rep.risk_code = RiskCode::Approved;
        rep.engine_result = OrderResult::Accepted;
        return rep;
    }

    static constexpr ExecutionReport make_modified(OrderId id, uint32_t inst, uint32_t client,
                                                   Side side, Price new_price, Quantity remaining_qty,
                                                   uint64_t exec_id, Timestamp ts = 0) noexcept {
        ExecutionReport rep{};
        rep.order_id = id;
        rep.exec_id = exec_id;
        rep.price = new_price;
        rep.last_qty = 0;
        rep.leaves_qty = remaining_qty;
        rep.timestamp = ts;
        rep.instrument_id = inst;
        rep.client_id = client;
        rep.exec_type = ExecutionType::Modified;
        rep.side = side;
        rep.risk_code = RiskCode::Approved;
        rep.engine_result = OrderResult::Accepted;
        return rep;
    }

    constexpr bool operator==(const ExecutionReport& other) const noexcept {
        return order_id == other.order_id &&
               exec_id == other.exec_id &&
               price == other.price &&
               last_qty == other.last_qty &&
               leaves_qty == other.leaves_qty &&
               timestamp == other.timestamp &&
               instrument_id == other.instrument_id &&
               client_id == other.client_id &&
               exec_type == other.exec_type &&
               side == other.side &&
               risk_code == other.risk_code &&
               engine_result == other.engine_result;
    }
};

static_assert(sizeof(ExecutionReport) == 64, "ExecutionReport must be exactly 64 bytes");
static_assert(alignof(ExecutionReport) == 64, "ExecutionReport must be 64-byte aligned");
static_assert(std::is_trivially_copyable_v<ExecutionReport>, "ExecutionReport must be trivially copyable");
static_assert(std::is_standard_layout_v<ExecutionReport>, "ExecutionReport must have standard layout");

inline std::ostream& operator<<(std::ostream& os, const ExecutionReport& rep) {
    return os << "ExecutionReport{id=" << rep.order_id
              << ", exec_id=" << rep.exec_id
              << ", type=" << rep.exec_type
              << ", side=" << rep.side
              << ", price=" << rep.price
              << ", last_qty=" << rep.last_qty
              << ", leaves_qty=" << rep.leaves_qty
              << ", risk=" << rep.risk_code
              << ", res=" << rep.engine_result << "}";
}

} // namespace hft
